spring: 
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/ecommdashboard"
    username: "root"
    password: "tarun"
    

server:
  port: 8088
  address: localhost
      
    